#![cfg(feature = "geodetic")]

//! Property tests for the great-circle arc primitives (`arc_bounding_box`,
//! `arc_contains_point`, `arc_distance_2`), independent of any tree or leaf type.
//!
//! The shared generators, the ternary-search arc oracle (`nearest_arc_c2`), and the
//! slerp sampler live in the [`geodetic_common`] module; `ARC_GOLDEN` below anchors both
//! the implementation and that oracle to an external high-precision reference.

mod geodetic_common;
use geodetic_common::{
    coord, draw_arc, draw_arc_near_180, draw_query_for_arc, nearest_arc_c2, sample_arc,
};

use hegel::generators;
use hegel::TestCase;

use rstar::geodetic::{arc_bounding_box, arc_distance_2};
use rstar::Envelope;

// --- properties ---

/// MINDIST containment: every sampled point of the arc embeds
/// inside its box. Boolean containment, no slack beyond the implementation's margin.
#[hegel::test(test_cases = 200)]
fn prop_arc_box_contains_arc(tc: TestCase) {
    let (a, b) = draw_arc(&tc);
    let bbox = arc_bounding_box(a.to_unit_vector(), b.to_unit_vector());
    for v in sample_arc(a, b, 256) {
        assert!(
            bbox.contains_point(&v),
            "box does not contain arc sample; a=({},{}) b=({},{})",
            a.lon,
            a.lat,
            b.lon,
            b.lat
        );
    }
}

/// The near-antipodal counterpart: the thin shell `draw_arc` misses, with many
/// renormalised samples and zero slack. Catches the u,v-frame undercoverage regime.
#[hegel::test(test_cases = 200)]
fn prop_arc_box_contains_arc_near_180(tc: TestCase) {
    let (a, b) = draw_arc_near_180(&tc);
    let bbox = arc_bounding_box(a.to_unit_vector(), b.to_unit_vector());
    for v in sample_arc(a, b, 1024) {
        assert!(
            bbox.contains_point(&v),
            "near-180 box does not contain arc sample; a=({},{}) b=({},{})",
            a.lon,
            a.lat,
            b.lon,
            b.lat
        );
    }
}

/// Tightness (backs MINMAXDIST): the box matches the AABB of a
/// dense arc sample within `TIGHT_TOL` per face, so no face is grossly over-inflated.
#[hegel::test(test_cases = 200)]
fn prop_arc_box_is_tight(tc: TestCase) {
    const TIGHT_TOL: f64 = 1e-6;
    let (a, b) = draw_arc(&tc);
    let bbox = arc_bounding_box(a.to_unit_vector(), b.to_unit_vector());
    let mut lo = [f64::INFINITY; 3];
    let mut hi = [f64::NEG_INFINITY; 3];
    for v in sample_arc(a, b, 2048) {
        for i in 0..3 {
            lo[i] = lo[i].min(v.0[i]);
            hi[i] = hi[i].max(v.0[i]);
        }
    }
    for i in 0..3 {
        assert!(
            (bbox.lower().0[i] - lo[i]).abs() <= TIGHT_TOL,
            "lower face {i} not tight: box {} vs sample {}; a=({},{}) b=({},{})",
            bbox.lower().0[i],
            lo[i],
            a.lon,
            a.lat,
            b.lon,
            b.lat
        );
        assert!(
            (bbox.upper().0[i] - hi[i]).abs() <= TIGHT_TOL,
            "upper face {i} not tight: box {} vs sample {}; a=({},{}) b=({},{})",
            bbox.upper().0[i],
            hi[i],
            a.lon,
            a.lat,
            b.lon,
            b.lat
        );
    }
}

/// Point-to-arc squared chord matches an independent ternary-search oracle, including
/// queries biased toward the arc's pole-of-circle (the
/// regime that exposes the projection cancellation the analytic form guards against).
#[hegel::test(test_cases = 5000)]
fn prop_point_to_geometry_matches_oracle(tc: TestCase) {
    let (a, b) = draw_arc(&tc);
    let q = draw_query_for_arc(&tc, a, b);
    let c2 = arc_distance_2(a.to_unit_vector(), b.to_unit_vector(), q.to_unit_vector());
    let expected = nearest_arc_c2(q, a, b);
    // Squared-chord tolerance: ~1e-7 sits four orders below the ~1e-3 c2 error a
    // nearest-point bug would produce and four orders above the analytic/ternary
    // numerical noise (~1e-11), so it catches the former without flagging the latter.
    let tol = 1e-7 + expected * 1e-9;
    assert!(
        (c2 - expected).abs() <= tol,
        "arc c2 {c2} != oracle {expected}; a=({},{}) b=({},{}) q=({},{})",
        a.lon,
        a.lat,
        b.lon,
        b.lat,
        q.lon,
        q.lat
    );
}

/// External ground truth for point-to-arc squared chord, regenerated by
/// `tests/reference/arc_distance_reference.py`: two algorithmically-independent `mpmath`
/// 60-digit methods (plane projection vs slerp minimisation) that agree to `< 1e-22`
/// radians, cross-checked against the `s2sphere` library. It shares no code with the
/// rstar implementation or the `nearest_arc_c2` oracle, so it anchors *both*: were the
/// oracle (which the property tests above trust) to drift from truth, this would catch
/// it. Columns: `a_lon, a_lat, b_lon, b_lat, q_lon, q_lat, golden_c2`.
#[rustfmt::skip]
const ARC_GOLDEN: &[(f64, f64, f64, f64, f64, f64, f64)] = &[
    (0.0, 0.0, 0.0, 80.0, 0.0, 40.0, 0.0),
    (0.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.00030460968721752167),
    (10.0, 0.0, 40.0, 0.0, 0.0, 90.0, 2.0),
    (-30.0, 0.0, 30.0, 0.0, 0.0, -10.0, 0.03038449397558388),
    (0.0, 0.0, 0.0, 1.192092896e-07, 0.0, 1.0, 0.00030460961459476073),
    (0.0, 90.0, -180.0, -1.0, 0.0, 0.0, 2.0),
    (-180.0, 0.0, -179.99999992312644, -9.111154769854667e-08, 0.0, 1.192092896e-07, 4.0),
    (0.0, 42.0, 79.70606382642427, 77.44802220072441, -101.56168723473104, 12.549002721292226, 1.9999999979999996),
    (170.0, 0.0, -170.0, 0.0, 179.0, 5.0, 0.007610603816508936),
    (0.0, 0.0, 90.0, 0.0, 45.0, 0.0001, 3.0461741978663128e-12),
    (0.0, 0.0, 10.0, 0.0, 5.0, 10.0, 0.03038449397558388),
    (-73.0, 40.0, 2.0, 48.0, -30.0, 55.0, 0.004339779116214164),
    (-26.560343599094153, -21.452506574757706, -16.86690674799354, -51.738153044234046, 9.520122231205335, -11.41873068720244, 0.3803602429096538),
    (-58.026368762626845, -57.4691500063426, 113.15807991626957, -0.8533079950642735, -80.76262108101673, 56.74945506526882, 2.866261925524996),
    (165.57179880222606, -4.289333341857997, -91.51396569812255, -78.40898828630255, 13.66254995219549, 80.66554142136087, 2.432985677115532),
    (-13.05393007773668, 38.5937288342935, 78.0292899500563, 6.196108897156627, 91.89638655965746, 24.850300884829522, 0.15662724808513642),
    (-16.556427489802275, -2.479568436910938, -53.16042328953819, 37.48317047625337, 148.1204596965748, -0.9234304513547187, 3.4982683673400468),
    (-88.6293587190396, -39.80866357521941, 48.94301143702148, 25.414117742810227, -18.413113347179916, 85.8417465535432, 1.0935129570693958),
    (-157.36842341008958, 8.217207828778825, 147.62413905207382, -40.06700523371138, -146.57675552558982, -36.32456301418247, 0.3694067667488645),
    (81.6591443742264, -20.151917848169745, 75.07767106699418, -27.467594191608743, 125.87570909011731, 0.23933701340588698, 0.6572222023839122),
    (176.3554034881792, 56.98186336207556, 3.331732032220998, -42.13243662909476, -149.74693916458043, -85.48429151723536, 0.7665920364760166),
    (-130.86215655618653, -85.93444866067102, -54.351371969945546, -26.715940703978603, 39.542804650361745, -16.36980701772032, 1.5718908481066711),
    (34.5263049009431, 84.68575261540656, 160.32207851177748, 14.914672648570885, 118.16511164488668, 61.55051533984272, 0.06908884418239569),
    (67.93466498280483, 19.86831430668181, 15.691897818790835, -46.91620540017943, -90.19845981023747, 52.672663217727404, 2.517986734490947),
    (45.433483365218876, -6.747675524803157, -21.46487860055663, -9.469602105170939, -103.89753359793315, -45.95871225254834, 1.5828644650875168),
    (-58.680099943272424, 40.38891862948796, 160.02751053637758, 80.06065210557166, 59.19961368772081, 62.17725144643197, 0.2880248035604991),
    (-124.46345188536333, 76.78360221651738, 152.18390438852032, 37.35022153476352, 60.074591788971134, 61.720498174118546, 0.4931211000050673),
    (-137.2541367235794, -79.87428919037552, 169.9572744427063, 23.233975205329475, 155.24848576425472, 55.381089965253835, 0.3408465519990229),
    (-148.82172971729418, 66.47081021264, -16.14377739391557, 71.67642689205455, 71.26573072374205, -84.29164401095171, 3.88537854406896),
    (-0.47185375976138744, 77.96754697776859, 55.91375687555217, -42.197423206686175, 48.543674257362426, 53.623273040120694, 0.01841858762408804),
    (12.930944413975027, -70.8680650900874, -115.8891451217745, -19.86092778072887, -58.81486628234799, -49.1323452232193, 0.14895466796149365),
    (34.49807384198266, -32.04663978679523, 32.35994222727618, -33.138469657009225, -83.96730037445579, 0.18448050749964295, 2.7462431762080963),
    (-167.50338593668755, 64.10174602499035, 178.04428529325673, 66.6164728391502, 31.071952163126127, 35.03630500175602, 1.4910161430759976),
    (-0.41875669523633974, 0.6863845912664175, 157.05648603824932, 37.944701577181284, -67.40474902917542, -68.99495723140008, 1.7421102308990073),
    (111.45963556294333, -39.11209207433565, 108.90208077643842, -33.283075026478166, 31.719340395801737, -69.57689734496974, 0.7211798507102198),
    (17.4930887240115, -14.61695389088834, 149.72428337361396, 3.668639558134606, 28.84941953330957, 55.95110322765123, 1.3558405202048538),
    (-97.60643135818056, 4.316918020144698, -113.91072911536719, -26.203178372030784, 8.03354871148116, -63.44814992435524, 1.6344382699750326),
    (-143.09058367195752, -50.594992124431165, -95.70980682991836, -46.65490839680762, 177.23503882115398, -3.5561641270256246, 0.9288386560565904),
    (-37.88735142102968, 14.095062389516727, -20.44975407417678, 42.15980932129854, 76.65545295020047, -44.49229788595961, 2.9161066559227002),
    (-55.82855304748904, -85.5529734416577, -86.26405614749797, -46.26508704937364, 73.26733999254668, -78.34501217444901, 0.06688930827020567),
    (-41.93141338172546, 60.94729287883453, 2.8810371424846153, 62.238117540287995, -138.69489703013906, 76.70152938171486, 0.324845897183457),
    (-30.60726477070068, -22.424679904315497, 7.326422296952387, -13.893050030944803, -14.935302296683517, 75.08547750402172, 2.001591658492456),
    (106.12315298214207, -39.89458282213788, 94.39090698110238, 28.085100380574634, -128.78482437302722, 54.080513023208454, 1.9923651579524762),
    (-95.26794337052387, 84.52966149530835, -2.16652975993361, 66.57429151259721, -26.96840994407495, 6.7514824760536385, 1.06747858571276),
    (-99.05809734552447, -7.1039663311085235, -160.5582137927015, -38.07668194278161, 171.30500116286726, -50.37284573646434, 0.16454261804655027),
    (103.81431675642358, 76.54156057040416, -164.1858094236677, 16.4028424039927, -73.10585902999793, 71.59684726447404, 0.29953296157864007),
    (166.1417065937099, 50.60636166906872, -84.81791464213643, 61.85873914621971, -78.77483386519937, 40.57733523267143, 0.14036319538714587),
    (11.671865223182209, -83.6690949213501, 23.388156990337734, 40.00479903491508, -169.94628902002177, -34.821176736952694, 1.0459087250742534),
    (-155.96789784240383, -35.507641765354, -149.69211936141005, 11.461608993229051, 145.19907935698188, -66.7815977644399, 0.6002801023859249),
    (72.39977875597702, 35.97918984383125, -14.300480113835306, 59.1920618921692, -46.778524763752216, -81.64352673146321, 3.277181289323664),
    (-16.298696852940765, 37.58981009500131, 37.94654058145636, 4.066548944577437, -48.80829031133777, 52.4088195724222, 0.21801309459325402),
    (-176.91093138119038, -77.79076370356321, 140.44797032718418, -67.90669229643198, 158.81767783013288, 3.331426029062044, 1.3949952359421545),
];

/// Validate both the implementation (`arc_distance_2`) and the test oracle
/// (`nearest_arc_c2`) against the external [`ARC_GOLDEN`] reference.
#[test]
fn arc_distance_and_oracle_match_external_reference() {
    for &(al, aa, bl, bb, ql, qa, gold) in ARC_GOLDEN {
        let (a, b, q) = (coord(al, aa), coord(bl, bb), coord(ql, qa));
        let implementation =
            arc_distance_2(a.to_unit_vector(), b.to_unit_vector(), q.to_unit_vector());
        let oracle = nearest_arc_c2(q, a, b);
        // The whole table matches to <= 1.33e-15 (f64 embedding-rounding floor); 1e-12
        // is comfortably above that and ~1e9 below the c2 error a real nearest-point bug
        // would produce, so it stays a meaningful anchor even for the ~3e-12 case.
        let tol = 1e-12 + gold * 1e-12;
        assert!(
            (implementation - gold).abs() <= tol,
            "impl c2 {implementation} != golden {gold}; a=({al},{aa}) b=({bl},{bb}) q=({ql},{qa})"
        );
        assert!(
            (oracle - gold).abs() <= tol,
            "oracle c2 {oracle} != golden {gold}; a=({al},{aa}) b=({bl},{bb}) q=({ql},{qa})"
        );
    }
}

/// Long-running soak that hunts for new point-to-arc counterexamples to promote into
/// [`ARC_GOLDEN`]. Ignored by default – a full run takes hours. Run it locally with
///
/// ```text
/// cargo nextest run -p rstar --features geodetic --run-ignored all -E 'test(soak_arc)'
/// ```
///
/// (or `cargo test -p rstar --features geodetic -- --ignored soak_arc`). The seed is fresh
/// on each local run (CI derandomises, local does not), so repeated runs explore new
/// inputs. At roughly a millisecond per case (Hegel's per-example cost dominates the
/// maths), 20 million cases is several hours; scale `test_cases` to taste, or re-run to
/// soak longer. On a disagreement Hegel shrinks and prints the minimal `(a, b, q)`; obtain
/// its ground-truth squared chord from `tests/reference/arc_distance_reference.py`, then
/// append the row to [`ARC_GOLDEN`].
///
/// Each case draws either a broad arc or one of the worst-conditioned kinds (near-antipodal
/// or pole-of-circle), so the soak stresses the general space and the hard corners together.
#[ignore = "long-running soak; run locally to find ARC_GOLDEN candidates"]
#[hegel::test(test_cases = 20_000_000)]
fn soak_arc_distance_vs_oracle(tc: TestCase) {
    let near_antipodal = tc.draw(generators::booleans());
    let (a, b) = if near_antipodal {
        draw_arc_near_180(&tc)
    } else {
        draw_arc(&tc)
    };
    let q = draw_query_for_arc(&tc, a, b);
    let c2 = arc_distance_2(a.to_unit_vector(), b.to_unit_vector(), q.to_unit_vector());
    let expected = nearest_arc_c2(q, a, b);
    let tol = 1e-7 + expected * 1e-9;
    let delta = (c2 - expected).abs();
    // Steer the search toward the largest disagreement instead of relying on uniform
    // exploration alone: target how close each case sits to its tolerance, labelled per
    // regime so the antipodal and broad branches are optimised independently rather than one
    // dominating. Normalising by tol keeps the regimes comparable (raw delta would
    // over-weight the near-antipodal c2 ~ 4 regime).
    tc.target_labelled(
        delta / tol,
        if near_antipodal { "antipodal" } else { "broad" },
    );
    assert!(
        delta <= tol,
        "arc_distance_2 and the oracle disagree by {delta} (tol {tol}): \
         impl {c2}, oracle {expected}.\nPromote it: add this case to CURATED in \
         tests/reference/arc_distance_reference.py, run that script, and append the \
         printed row to ARC_GOLDEN:\n    ({}, {}, {}, {}, {}, {}),",
        a.lon,
        a.lat,
        b.lon,
        b.lat,
        q.lon,
        q.lat
    );
}
