name: Run tests

on:
  push:
    branches:
      - master
      - main
      - staging
      - release/**
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: test
      - run: cargo test --package rstar
      - run: cargo test --package rstar --features geodetic

  check:
    name: Rustfmt and Clippy check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check formatting using Rustfmt
        run: cargo fmt --all --check
      - name: Lint using Clippy
        run: cargo clippy --workspace --exclude rstar-demo --tests
      - name: Lint geodetic feature using Clippy
        run: cargo clippy --package rstar --features geodetic --all-targets -- -D warnings

  msrv:
    name: MSRV build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@1.85.0
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: msrv
      - name: Run cargo build for MSRV
        run: cargo build --package rstar

  no_std:
    name: no_std build
    runs-on: ubuntu-latest
    env:
      NO_STD_TARGET: aarch64-unknown-none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{env.NO_STD_TARGET}}
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: no-std-${{env.NO_STD_TARGET}}
      - name: Run cargo build for ${{env.NO_STD_TARGET}}
        run: cargo build --package rstar --target ${{env.NO_STD_TARGET}}
      - name: Run cargo build for ${{env.NO_STD_TARGET}} with geodetic feature
        run: cargo build --package rstar --features geodetic --target ${{env.NO_STD_TARGET}}

  conclusion:
    needs:
      - test
      - check
      - msrv
      - no_std
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Result
        run: |
          jq -C <<< "${needs}"
          # Check if all needs were successful or skipped.
          "$(jq -r 'all(.result as $result | (["success", "skipped"] | contains([$result])))' <<< "${needs}")"
        env:
          needs: ${{ toJson(needs) }}
